mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba" "D:\Dropbox\jamba\Jamba-Legion\Jamba"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-AdvancedLoot" "D:\Dropbox\jamba\Jamba-Legion\Jamba-AdvancedLoot"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Curr" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Curr"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-DisplayTeam" "D:\Dropbox\jamba\Jamba-Legion\Jamba-DisplayTeam"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Follow" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Follow"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-FTL" "D:\Dropbox\jamba\Jamba-Legion\Jamba-FTL"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-ItemUse" "D:\Dropbox\jamba\Jamba-Legion\Jamba-ItemUse"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Macro" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Macro"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Purchase" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Purchase"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Quest" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Quest"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-QuestWatcher" "D:\Dropbox\jamba\Jamba-Legion\Jamba-QuestWatcher"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Sell" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Sell"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Talk" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Talk"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Target" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Target"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Taxi" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Taxi"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Toon" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Toon"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Trade" "D:\Dropbox\jamba\Jamba-Legion\Jamba-Trade"

