mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-AdvancedLoot" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-AdvancedLoot"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Curr" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Curr"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-DisplayTeam" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-DisplayTeam"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Follow" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Follow"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-FTL" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-FTL"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-ItemUse" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-ItemUse"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Macro" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Macro"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Purchase" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Purchase"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Quest" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Quest"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-QuestWatcher" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-QuestWatcher"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Sell" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Sell"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Talk" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Talk"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Target" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Target"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Taxi" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Taxi"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Toon" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Toon"
mklink /d "D:\World of Warcraft Public Test\Interface\addons\Jamba-Trade" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Trade"
mklink /d "C:\Program Files (x86)\World of Warcraft Beta\interface\addons\Jamba-Mount" "C:\Users\ebony.CARBONSPACE\OneDrive\jamba\Jamba-Legion\Jamba-Mount"

